contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Hunt using available tools
id: Search Endpoints By Hash - Generic V2
inputs:
- description: MD5 Hash
  key: MD5Hash
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: SHA1 Hash
  key: SHA1Hash
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
- description: SHA256 Hash
  key: SHA256Hash
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
name: Search Endpoints By Hash - Generic V2
outputs:
- contextPath: Endpoint.Hostname
  description: Device hostname
  type: string
- contextPath: Endpoint
  description: The endpoint
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 92368958-9a49-4dcc-8db9-b15d29c87e29
      iscommand: false
      name: ""
      version: -1
    taskid: 92368958-9a49-4dcc-8db9-b15d29c87e29
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 410,
          "y": 10
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      FileSha256:
        complex:
          root: inputs.SHA256Hash
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook is part of the 'Malware Investigation And Response'
        pack. For more information, refer to https://xsoar.pan.dev/docs/reference/packs/malware-investigation-and-response.
        This playbook searches across the organization for other endpoints associated
        with a specific SHA256 hash.
      id: b66537ca-cc94-4509-8985-3bb247c163a9
      iscommand: false
      name: CrowdStrike Falcon - Search Endpoints By Hash
      playbookName: CrowdStrike Falcon - Search Endpoints By Hash
      type: playbook
      version: -1
    taskid: b66537ca-cc94-4509-8985-3bb247c163a9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -10,
          "y": 590
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      Hash:
        complex:
          accessor: MD5Hash
          root: inputs
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Hunt for endpoint activity involving hash IOCs, using Carbon Black
        Protection.
      id: 481954b9-682a-4722-8790-1547663edb81
      iscommand: false
      name: Search Endpoints By Hash - Carbon Black Protection
      playbookName: Search Endpoints By Hash - Carbon Black Protection
      type: playbook
      version: -1
    taskid: 481954b9-682a-4722-8790-1547663edb81
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 590
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eab5a3b4-3b54-401c-82f9-afbb033b2de3
      iscommand: false
      name: MD5 Only
      type: title
      version: -1
    taskid: eab5a3b4-3b54-401c-82f9-afbb033b2de3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 898,
          "y": 160
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
      - "15"
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b4804466-0b8c-4c96-89e7-3bbed13670ad
      iscommand: false
      name: MD5 / SHA1 / SHA256
      type: title
      version: -1
    taskid: b4804466-0b8c-4c96-89e7-3bbed13670ad
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -20,
          "y": 160
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: MD5Hash
                root: inputs
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "8"
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is MD5 hash?
      id: d6de96ed-bf55-40bb-887a-3821358bf89c
      iscommand: false
      name: Is MD5 hash?
      type: condition
      version: -1
    taskid: d6de96ed-bf55-40bb-887a-3821358bf89c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 898,
          "y": 320
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4b3639ac-2625-446f-8f8a-a534ee676494
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4b3639ac-2625-446f-8f8a-a534ee676494
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 810
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      Hash:
        simple: ${.=Object.keys(val.inputs).map(function(f) { return val.inputs[f];
          }).reduce(function(a, b){ return a.concat(b); }, [])}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

        Input:
        * Hash (default, takes all deferent hashes from context)

        Output:
        * All agents that files with "Hash" has been executed on (TIE)
        * Enrich Agents info from ePO
      id: 9a79dca5-a826-494e-8444-87f03331bbe4
      iscommand: false
      name: Search Endpoints By Hash - TIE
      playbookName: Search Endpoints By Hash - TIE
      type: playbook
      version: -1
    taskid: 9a79dca5-a826-494e-8444-87f03331bbe4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 410,
          "y": 320
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      MD5Hash:
        complex:
          root: inputs.MD5Hash
      SHA1Hash:
        complex:
          root: inputs.SHA1Hash
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Hunt for endpoint activity involving hash, using Cybereason.
      id: 96ea4595-3ac2-41be-85f1-9ffe6ac7df6c
      iscommand: false
      name: Search Endpoints By Hash - Cybereason
      playbookName: Search Endpoints By Hash - Cybereason
      type: playbook
      version: -1
    taskid: 96ea4595-3ac2-41be-85f1-9ffe6ac7df6c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -460,
          "y": 320
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      Hash:
        complex:
          root: inputs.MD5Hash
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Hunt for malicious indicators using Carbon Black
      id: 54f36ae2-15fa-42cb-8b77-62e48c8e50c4
      iscommand: false
      name: Search Endpoints By Hash - Carbon Black Response V2
      playbookName: Search Endpoints By Hash - Carbon Black Response V2
      type: playbook
      version: -1
    taskid: 54f36ae2-15fa-42cb-8b77-62e48c8e50c4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 720,
          "y": 590
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256Hash
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 58684e15-2a09-47d2-879c-c374af670aa7
      iscommand: false
      name: Is SHA256 hash?
      type: condition
      version: -1
    taskid: 58684e15-2a09-47d2-879c-c374af670aa7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -20,
          "y": 320
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_16_yes": 0.47,
      "11_8_yes": 0.58,
      "17_12_#default#": 0.27
    },
    "paper": {
      "dimensions": {
        "height": 865,
        "width": 1970,
        "x": -460,
        "y": 10
      }
    }
  }
