contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 2.6.10
    packID: VirusTotal
    packName: VirusTotal
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Get file information using the Virus Total API integration.
id: File Enrichment - Virus Total (API v3)
inputs:
- description: File Hash to enrich
  key: FileHash
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - args:
          item:
            iscontext: true
            value:
              simple: File.SHA1
        operator: append
      - args:
          item:
            iscontext: true
            value:
              simple: File.MD5
        operator: append
name: File Enrichment - Virus Total (API v3)
outputs:
- contextPath: File.MD5
  description: Bad MD5 hash.
  type: Unknown
- contextPath: File.SHA1
  description: Bad SHA1 hash.
  type: Unknown
- contextPath: File.SHA256
  description: Bad SHA256 hash.
  type: Unknown
- contextPath: File.Relationships.EntityA
  description: The source of the relationship.
  type: String
- contextPath: File.Relationships.EntityB
  description: The destination of the relationship.
  type: String
- contextPath: File.Relationships.Relationship
  description: The name of the relationship.
  type: String
- contextPath: File.Relationships.EntityAtype
  description: The type of the source of the relationship.
  type: String
- contextPath: File.Relationships.EntityBtype
  description: The type of the destination of the relationship.
  type: String
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision.
  type: Unknown
- contextPath: File.Malicious.Detections
  description: For malicious files, the total number of detections.
  type: Unknown
- contextPath: File.Malicious.TotalEngines
  description: For malicious files, the total number of engines that checked the file
    hash.
  type: Unknown
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: Unknown
- contextPath: DBotScore.type
  description: The indicator type.
  type: Unknown
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the DBot score.
  type: Unknown
- contextPath: DBotScore.Score
  description: The actual score.
  type: Number
- contextPath: DBotScore.Reliability
  description: Reliability of the source providing the intelligence data.
  type: String
- contextPath: VirusTotal.File.attributes.type_description
  description: description of the type of the file.
  type: String
- contextPath: VirusTotal.File.attributes.tlsh
  description: The locality-sensitive hashing.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.MIMEtype
  description: MIME type of the file.
  type: String
- contextPath: VirusTotal.File.attributes.names
  description: Names of the file.
  type: String
- contextPath: VirusTotal.File.attributes.javascript_info.tags
  description: Tags of the JavaScript.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.Filetype
  description: The file type.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.WordCount
  description: Total number of words in the file.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.LineCount
  description: Total number of lines in file.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_ids_stats.info
  description: Number of IDS that marked the file as "info".
  type: Number
- contextPath: VirusTotal.File.attributes.crowdsourced_ids_stats.high
  description: Number of IDS that marked the file as "high".
  type: Number
- contextPath: VirusTotal.File.attributes.crowdsourced_ids_stats.medium
  description: Number of IDS that marked the file as "medium".
  type: Number
- contextPath: VirusTotal.File.attributes.crowdsourced_ids_stats.low
  description: Number of IDS that marked the file as "low".
  type: Number
- contextPath: VirusTotal.File.attributes.sigma_analysis_stats.critical
  description: Number of Sigma analysis that marked the file as "critical".
  type: Number
- contextPath: VirusTotal.File.attributes.sigma_analysis_stats.high
  description: Number of Sigma analysis that marked the file as "high".
  type: Number
- contextPath: VirusTotal.File.attributes.sigma_analysis_stats.medium
  description: Number of Sigma analysis that marked the file as "medium".
  type: Number
- contextPath: VirusTotal.File.attributes.sigma_analysis_stats.low
  description: Number of Sigma analysis that marked the file as "low".
  type: Number
- contextPath: VirusTotal.File.attributes.exiftool.MIMEEncoding
  description: The MIME encoding.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.FiletypeExtension
  description: The file type extension.
  type: String
- contextPath: VirusTotal.File.attributes.exiftool.Newlines
  description: Number of newlines signs.
  type: String
- contextPath: VirusTotal.File.attributes.trid.file_type
  description: The TrID file type.
  type: String
- contextPath: VirusTotal.File.attributes.trid.probability
  description: The TrID probability.
  type: Number
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.description
  description: description of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.source
  description: Source of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.author
  description: Author of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.ruleset_name
  description: Rule set name of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.rule_name
  description: Name of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.crowdsourced_yara_results.ruleset_id
  description: ID of the YARA rule.
  type: String
- contextPath: VirusTotal.File.attributes.names
  description: Name of the file.
  type: String
- contextPath: VirusTotal.File.attributes.last_modification_date
  description: The last modification date in epoch format.
  type: Number
- contextPath: VirusTotal.File.attributes.type_tag
  description: Tag of the type.
  type: String
- contextPath: VirusTotal.File.attributes.total_votes.harmless
  description: Total number of harmless votes.
  type: Number
- contextPath: VirusTotal.File.attributes.total_votes.malicious
  description: Total number of malicious votes.
  type: Number
- contextPath: VirusTotal.File.attributes.size
  description: Size of the file.
  type: Number
- contextPath: VirusTotal.File.attributes.popular_threat_classification.suggested_threat_label
  description: Suggested thread label.
  type: String
- contextPath: VirusTotal.File.attributes.popular_threat_classification.popular_threat_name
  description: The popular thread name.
  type: Number
- contextPath: VirusTotal.File.attributes.times_submitted
  description: Number of times the file was submitted.
  type: Number
- contextPath: VirusTotal.File.attributes.last_submission_date
  description: Last submission date in epoch format.
  type: Number
- contextPath: VirusTotal.File.attributes.downloadable
  description: Whether the file is downloadable.
  type: Boolean
- contextPath: VirusTotal.File.attributes.sha256
  description: SHA-256 hash of the file.
  type: String
- contextPath: VirusTotal.File.attributes.type_extension
  description: Extension of the type.
  type: String
- contextPath: VirusTotal.File.attributes.tags
  description: File tags.
  type: String
- contextPath: VirusTotal.File.attributes.last_analysis_date
  description: Last analysis date in epoch format.
  type: Number
- contextPath: VirusTotal.File.attributes.unique_sources
  description: Unique sources.
  type: Number
- contextPath: VirusTotal.File.attributes.first_submission_date
  description: First submission date in epoch format.
  type: Number
- contextPath: VirusTotal.File.attributes.ssdeep
  description: SSDeep hash of the file.
  type: String
- contextPath: VirusTotal.File.attributes.md5
  description: MD5 hash of the file.
  type: String
- contextPath: VirusTotal.File.attributes.sha1
  description: SHA-1 hash of the file.
  type: String
- contextPath: VirusTotal.File.attributes.magic
  description: Identification of file by the magic number.
  type: String
- contextPath: VirusTotal.File.attributes.last_analysis_stats.harmless
  description: The number of engines that found the indicator to be harmless.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.type-unsupported
  description: The number of engines that found the indicator to be of type unsupported.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.suspicious
  description: The number of engines that found the indicator to be suspicious.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.confirmed-timeout
  description: The number of engines that confirmed the timeout of the indicator.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.timeout
  description: The number of engines that timed out for the indicator.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.failure
  description: The number of failed analysis engines.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.malicious
  description: The number of engines that found the indicator to be malicious.
  type: Number
- contextPath: VirusTotal.File.attributes.last_analysis_stats.undetected
  description: The number of engines that could not detect the indicator.
  type: Number
- contextPath: VirusTotal.File.attributes.meaningful_name
  description: Meaningful name of the file.
  type: String
- contextPath: VirusTotal.File.attributes.reputation
  description: The reputation of the file.
  type: Number
- contextPath: VirusTotal.File.type
  description: type of the indicator (file).
  type: String
- contextPath: VirusTotal.File.id
  description: type ID of the indicator.
  type: String
- contextPath: VirusTotal.File.links.self
  description: Link to the response.
  type: Unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cdcd5ce3-8d4a-4981-89ff-e94904ef9de0
      iscommand: false
      name: ""
      version: -1
    taskid: cdcd5ce3-8d4a-4981-89ff-e94904ef9de0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1155,
          "y": -23
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e5be9a7a-708a-4976-84de-f60213e157f0
      iscommand: false
      name: Enrich using VirusTotal (API v3)
      type: title
      version: -1
    taskid: e5be9a7a-708a-4976-84de-f60213e157f0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1585,
          "y": 370
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10dbc242-e1c6-4746-852e-3777185de510
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 10dbc242-e1c6-4746-852e-3777185de510
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1155,
          "y": 750
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: VirusTotal (API v3)
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Virus Total Private
        API enabled.
      id: 3d9a4d8a-9a38-45a5-86d0-d9707b8f9bf1
      iscommand: false
      name: Is VirusTotal (API v3) enabled?
      type: condition
      version: -1
    taskid: 3d9a4d8a-9a38-45a5-86d0-d9707b8f9bf1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1155,
          "y": 151
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${inputs.FileHash}
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the file reputation of the specified hash.
      id: 6bbaad1d-e54f-4da5-8416-5cd6e60fc026
      iscommand: true
      name: 'Enriching file reputation '
      script: VirusTotal (API v3)|||file
      type: regular
      version: -1
    taskid: 6bbaad1d-e54f-4da5-8416-5cd6e60fc026
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 560
        }
      }
  "30":
    continueonerror: true
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.FileHash
              operator: isNotEmpty
          root: inputs.FileHash
      retry-count:
        simple: "2"
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Retrieves a behavioral relationship of the given file hash.
      id: 223709ce-d1e9-46c7-8515-13d6bc6fa139
      iscommand: true
      name: Enriching a behavioral relationship
      script: VirusTotal (API v3)|||vt-file-sandbox-report
      type: regular
      version: -1
    taskid: 223709ce-d1e9-46c7-8515-13d6bc6fa139
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1380,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 838,
        "width": 1015,
        "x": 1155,
        "y": -23
      }
    }
  }
