contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |2-

  ## Generic Cloud Enrichment Playbook

  The **Cloud Enrichment - Generic Playbook** is designed to unify all the relevant playbooks concerning the enrichment of information in the cloud. It provides a standardized approach to enriching information in cloud environments.

  ### Supported Blocks

  1. **Cloud IAM Enrichment - Generic**
     - Enriches information related to Identity and Access Management (IAM) in the cloud.

  2. **Cloud Compute Enrichment - Generic**
     - Enriches information related to cloud compute resources.

  The playbook supports a single CSP enrichment at a time.
id: Cloud Enrichment - Generic
inputs:
- description: |-
    The cloud provider involved.
    The supported CSPs are AWS, Azure and GCP.
  key: cloudProvider
  playbookInputQuery: null
  required: false
  value: {}
- description: The instance name.
  key: instanceName
  playbookInputQuery: null
  required: false
  value: {}
- description: The instance ID.
  key: instanceID
  playbookInputQuery: null
  required: false
  value: {}
- description: The zone holding the instance.
  key: zone
  playbookInputQuery: null
  required: false
  value: {}
- description: The region holding the instance.
  key: region
  playbookInputQuery: null
  required: false
  value: {}
- description: The instance's resource group.
  key: azureResourceGroup
  playbookInputQuery: null
  required: false
  value: {}
- description: The username involved.
  key: username
  playbookInputQuery: null
  required: false
  value: {}
- description: The GCP project name.
  key: GCPProjectName
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    The type of the GCP identity.
    Can be either Service Account or a user.
  key: cloudIdentityType
  playbookInputQuery: null
  required: false
  value: {}
name: Cloud Enrichment - Generic
outputs:
- contextPath: AWS.EC2.Instances
  description: The instances.
  type: unknown
- contextPath: AWS.EC2.Instances.NetworkInterfaces
  description: The network interfaces for the instance.
  type: unknown
- contextPath: GoogleCloudCompute.Instances
  description: The instances.
  type: unknown
- contextPath: GoogleCloudCompute.Instances.networkInterfaces
  description: An array of network configurations for this instance. These specify
    how interfaces are configured to interact with other network services, such as
    connecting to the internet. Multiple interfaces are supported per instance.
- contextPath: GoogleCloudCompute.Instances.disks
  description: Array of disks associated with this instance. Persistent disks must
    be created before you can assign them.
- contextPath: GoogleCloudCompute.Instances.metadata
  description: The metadata key/value pairs assigned to this instance. This includes
    custom metadata and predefined keys.
- contextPath: GoogleCloudCompute.Instances.scheduling
  description: Sets the scheduling options for this instance.
- contextPath: Azure.Compute
  description: The VMs.
  type: unknown
- contextPath: AWS.IAM.Users
  description: |-
    AWS AM Users include:
    UserId
    Arn
    CreateDate
    Path
    PasswordLastUsed
  type: unknown
- contextPath: AWS.IAM.UserPolicies
  description: AWS IAM - user inline policies.
  type: unknown
- contextPath: AWS.IAM.AttachedUserPolicies
  description: AWS IAM - User attached policies.
  type: unknown
- contextPath: AWS.IAM.Users.AccessKeys
  description: |-
    AWS IAM Users Access Keys include:
    AccessKeyId
    Status
    CreateDate
    UserName
  type: unknown
- contextPath: AWS.IAM.Users.Groups
  description: AWS IAM - User groups.
  type: unknown
- contextPath: GCPIAM
  description: GCP IAM information.
  type: unknown
- contextPath: GSuite
  description: GSuite user information.
  type: unknown
- contextPath: MSGraphUser
  description: MSGraph user information.
  type: unknown
- contextPath: MSGraphGroups
  description: MSGraph groups information.
  type: unknown
- contextPath: MSGraphGroup
  description: MSGraph group information.
  type: unknown
- contextPath: GSuite.PageToken
  description: Token to specify the next page in the list.
  type: unknown
- contextPath: MSGraph.identityProtection
  description: MSGraph identity protection - risky user history.
  type: unknown
- contextPath: AWS.IAM.Users.AccessKeys.CreateDate
  description: The date when the access key was created.
- contextPath: AWS.IAM.Users.AccessKeys.UserName
  description: The name of the IAM user that the key is associated with.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 22defffa-e0d3-4818-88f0-f06649899f77
      iscommand: false
      name: ""
      version: -1
    taskid: 22defffa-e0d3-4818-88f0-f06649899f77
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 230,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      azureResourceGroup:
        complex:
          root: inputs.azureResourceGroup
      cloudProvider:
        complex:
          root: inputs.cloudProvider
      instanceID:
        complex:
          root: inputs.instanceID
      instanceName:
        complex:
          root: inputs.instanceName
      region:
        complex:
          root: inputs.region
      zone:
        complex:
          root: inputs.zone
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: cb7ff971-4a63-4338-8fd0-0e3c6b383627
      iscommand: false
      name: Cloud Compute Enrichment - Generic
      playbookId: Cloud Compute Enrichment - Generic
      type: playbook
      version: -1
    taskid: cb7ff971-4a63-4338-8fd0-0e3c6b383627
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 10,
          "y": 190
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ca18fe4c-e928-4db8-8fb5-a00f434242ba
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ca18fe4c-e928-4db8-8fb5-a00f434242ba
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 230,
          "y": 360
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      GCPProjectName:
        complex:
          root: inputs.GCPProjectName
      cloudIdentityType:
        complex:
          root: inputs.cloudIdentityType
      cloudProvider:
        complex:
          root: inputs.cloudProvider
      username:
        complex:
          root: inputs.username
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook is responsible for collecting and enriching data
        on Identity Access Management (IAM) in cloud environments (AWS, Azure, and
        GCP).
      id: 6112c304-54e5-4954-85d2-44b1e4e9ab75
      iscommand: false
      name: Cloud IAM Enrichment - Generic
      playbookId: Cloud IAM Enrichment - Generic
      type: playbook
      version: -1
    taskid: 6112c304-54e5-4954-85d2-44b1e4e9ab75
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 375,
        "width": 820,
        "x": 10,
        "y": 50
      }
    }
  }
