contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This playbook retrieves forensics from hosts for the following integrations:\n
  - Illusive Networks \n - Microsoft Defender For Endpoint"
id: Get host forensics - Generic
inputs:
- description: 'If using the Illusive Networks integration to retrieve additional
    forensics, provide the host fqdn_or_ip from which to get the forensics. '
  key: fqdn_or_ip
  playbookInputQuery: null
  required: false
  value: {}
- description: Date_range must be "number date_range_unit", for example 2 hours, 4
    minutes, 6 months, 1 day.
  key: start_date
  playbookInputQuery: null
  required: false
  value: {}
- description: Date_range must be "number date_range_unit" for example 2 hours, 4
    minutes, 6 months, 1 day.
  key: end_date
  playbookInputQuery: null
  required: false
  value: {}
- description: Provide the machine IDs of the systems you want to retrieve.
  key: machine_ID
  playbookInputQuery: null
  required: false
  value: {}
name: Get host forensics - Generic
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f20f2deb-51b2-43bc-8c19-ea19d795c1ce
      iscommand: false
      name: ""
      version: -1
    taskid: f20f2deb-51b2-43bc-8c19-ea19d795c1ce
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: IllusiveNetworks
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the Illusive Networks integration is enabled.
      id: 44e2bef7-db14-418e-8899-05b87ce087c1
      iscommand: false
      name: Is illusive enabled
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 44e2bef7-db14-418e-8899-05b87ce087c1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a407e17a-7005-4b1a-87c0-00e1e1c2cae2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a407e17a-7005-4b1a-87c0-00e1e1c2cae2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      end_date:
        simple: ${inputs.end_date}
      fqdn_or_ip:
        simple: ${inputs.fqdn_or_ip}
      start_date:
        simple: ${inputs.start_date}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 4e87acfb-c838-448f-8c35-a81c306b37bf
      iscommand: false
      name: Illusive-Collect-Forensics-On-Demand
      playbookName: Illusive-Collect-Forensics-On-Demand
      type: playbook
      version: -1
    taskid: 4e87acfb-c838-448f-8c35-a81c306b37bf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -30,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: Microsoft Defender Advanced Threat Protection
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the Microsoft Defender for Endpoint integration
        brand is enabled.
      id: c7004145-36f8-47b3-8bbf-b08852b7b00c
      iscommand: false
      name: Is Microsoft Defender For Endpoint Integration Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: c7004145-36f8-47b3-8bbf-b08852b7b00c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 195
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      AutoCollectinvestigationPackege:
        simple: "True"
      Hostnames:
        simple: ${inputs.fqdn_or_ip}
      IPs:
        simple: ${inputs.fqdn_or_ip}
      MachineIDs:
        simple: ${inputs.machine_ID}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: "This playbook simplifies retrieving investigation packages to
        Cortex XSOAR from supported machines (See https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/collect-investigation-package?view=o365-worldwide).
        \n\n The playbook receives information about the target devices (host name,
        IP, and device ID), validates the devices exist, and retrieves the collection
        package from those machines into the Cortex XSOAR console. \n Note: This action
        may take time, the average package size is around ~15 MB."
      id: 1fb6f15e-7c4b-429b-8974-e30dcac00512
      iscommand: false
      name: Microsoft Defender For Endpoint - Collect investigation package
      playbookName: Microsoft Defender For Endpoint - Collect investigation package
      type: playbook
      version: -1
    taskid: 1fb6f15e-7c4b-429b-8974-e30dcac00512
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 795,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 1205,
        "x": -30,
        "y": 50
      }
    }
  }
