contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Calculates and sets the incident severity based on the combination of
  the current incident severity, and the severity returned from the Evaluate Severity
  - Set By Highest DBotScore playbook.
id: Calculate Severity - Standard
inputs:
- description: A list of DBotScores of indicators.
  key: DBotScore
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: DBotScore
name: Calculate Severity - Standard
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39518188-8725-4c70-8f80-3a9a4554deb2
      iscommand: false
      name: ""
      version: -1
    taskid: 39518188-8725-4c70-8f80-3a9a4554deb2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      severity:
        simple: low
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity of the incident to "Low".
      id: d750bb71-4ef5-4de1-88ec-02d5035a0177
      iscommand: true
      name: Set incident severity to "Low"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d750bb71-4ef5-4de1-88ec-02d5035a0177
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 175,
          "y": 570
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      severity:
        simple: medium
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity of the incident to "Medium".
      id: 9c7487d4-53f2-4645-8f7b-2653d6c76676
      iscommand: true
      name: Set incident severity to "Medium"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 9c7487d4-53f2-4645-8f7b-2653d6c76676
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 580,
          "y": 570
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      severity:
        simple: high
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity of the incident to "High".
      id: 77f20a17-499a-4ed3-85ad-a24e697b4792
      iscommand: true
      name: Set incident severity to "High"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 77f20a17-499a-4ed3-85ad-a24e697b4792
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1243,
          "y": 570
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 84feda52-060b-4e27-89ef-05553ca57636
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 84feda52-060b-4e27-89ef-05553ca57636
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 900
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      severity:
        simple: critical
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity of the incident to "Critical".
      id: ffcb1963-a04f-4f3b-8ff8-37e6829ac96c
      iscommand: true
      name: Set incident severity to "Critical"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: ffcb1963-a04f-4f3b-8ff8-37e6829ac96c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1650,
          "y": 570
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.IncidentSeverity
                    operator: isEqualNumber
                    right:
                      value:
                        simple: "4"
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.DBotScoreSeverity
                    operator: isEqualString
                    right:
                      value:
                        simple: critical
                root: Severities
          operator: isExists
      label: Critical
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.IncidentSeverity
                    operator: isEqualNumber
                    right:
                      value:
                        simple: "3"
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.DBotScoreSeverity
                    operator: isEqualString
                    right:
                      value:
                        simple: high
                root: Severities
          operator: isExists
      label: High
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.IncidentSeverity
                    operator: isEqualNumber
                    right:
                      value:
                        simple: "2"
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.DBotScoreSeverity
                    operator: isEqualString
                    right:
                      value:
                        simple: medium
                root: Severities
          operator: isExists
      label: Medium
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.IncidentSeverity
                    operator: isEqualNumber
                    right:
                      value:
                        simple: "1"
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severities.DBotScoreSeverity
                    operator: isEqualString
                    right:
                      value:
                        simple: low
                root: Severities
          operator: isExists
      label: Low
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      Critical:
      - "11"
      High:
      - "6"
      Low:
      - "4"
      Medium:
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines and sets the incident severity based on the highest
        result of all severity calculations.
      id: 14b9554d-23ca-4e85-86f8-51f290b2a18d
      iscommand: false
      name: Set severity based on the highest severity
      type: condition
      version: -1
    taskid: 14b9554d-23ca-4e85-86f8-51f290b2a18d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Severities.IncidentSeverity
      value:
        complex:
          accessor: severity
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Saves the incident severity in context.
      id: dd9d54b5-409c-4bd2-82d3-62785b06c406
      iscommand: false
      name: Get incident severity
      script: Set
      type: regular
      version: -1
    taskid: dd9d54b5-409c-4bd2-82d3-62785b06c406
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 195
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      DBotScore:
        complex:
          root: inputs.DBotScore
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Calculates the incident severity level according to the indicator
        with the highest DBotScore.
      id: 64da7797-a618-454e-8243-37cfde94d1c5
      iscommand: false
      name: Evaluate Severity - Set By Highest DBotScore
      playbookId: Calculate Severity By Highest DBotScore
      type: playbook
      version: -1
    taskid: 64da7797-a618-454e-8243-37cfde94d1c5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 620,
          "y": 195
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      severity:
        simple: unknown
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the incident severity to "Unknown".
      id: c78dbddd-05c3-4810-8b62-9a0f5958dc73
      iscommand: true
      name: Set incident severity to "Unknown"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: c78dbddd-05c3-4810-8b62-9a0f5958dc73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "15_11_Critical": 0.84,
      "15_19_#default#": 0.5,
      "15_4_Low": 0.85
    },
    "paper": {
      "dimensions": {
        "height": 915,
        "width": 1855,
        "x": 175,
        "y": 50
      }
    }
  }
