contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Hunt for assets with a given CVE using available tools
id: Search Endpoint by CVE - Generic
inputs:
- description: The CVE ID
  key: CVE_ID
  playbookInputQuery: null
  required: false
  value: {}
name: Search Endpoint by CVE - Generic
outputs:
- contextPath: Kenna.Assets
  description: Compromised Assets from Kenna
  type: unknown
- contextPath: Nexpose.Asset
  description: Compromised Assets from Nexpose
  type: unknown
- contextPath: Endpoint
  description: Global compromised Assets
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3cc9f67a-3dcb-4793-8ac2-fbbeac13430c
      iscommand: false
      name: ""
      version: -1
    taskid: 3cc9f67a-3dcb-4793-8ac2-fbbeac13430c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -20,
          "y": 60
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.CVE_ID
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is a CVE in the playbook input
      id: fe3f943e-ee9d-4e14-8d38-acd5029ebbb9
      iscommand: false
      name: Is there CVE?
      type: condition
      version: -1
    taskid: fe3f943e-ee9d-4e14-8d38-acd5029ebbb9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -20,
          "y": 240
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
      - "7"
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5c6efc1c-e322-4f05-875b-e1e9410adf25
      iscommand: false
      name: Search CVE
      type: title
      version: -1
    taskid: 5c6efc1c-e322-4f05-875b-e1e9410adf25
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 800,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 776c24cb-8546-4e9c-81f7-cfd2dc6c4727
      iscommand: false
      name: Rapid7 Nexpose
      type: title
      version: -1
    taskid: 776c24cb-8546-4e9c-81f7-cfd2dc6c4727
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 230,
          "y": 560
        }
      }
  "4":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isEqualString
          right:
            value:
              simple: Rapid7 Nexpose
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Checks if Rapid7 Nexpose is enabled '
      id: 70b1a735-db7c-4d65-8b8f-ac8f1eaa212f
      iscommand: false
      name: Is Rapid7 Nexpose enabled?
      type: condition
      version: -1
    taskid: 70b1a735-db7c-4d65-8b8f-ac8f1eaa212f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 230,
          "y": 700
        }
      }
  "5":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Breached Compromised Hosts
      output:
        complex:
          accessor: Asset
          root: Nexpose
          transformers:
          - operator: ConvertToSingleElementArray
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      vulnerabilityTitleContains:
        complex:
          root: inputs.CVE_ID
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Search and return all assets matching specific filters. Returns
        only assets the user has access to.
      id: 14333e5c-cb15-4a68-8445-2b05472229e1
      iscommand: true
      name: 'Search CVE with Rapid7 Nexpose '
      script: '|||nexpose-search-assets'
      tags:
      - autoCVEsearch
      type: regular
      version: -1
    taskid: 14333e5c-cb15-4a68-8445-2b05472229e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 910
        }
      }
  "6":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isEqualString
          right:
            value:
              simple: Kennav2
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Checks if KennaV2 is enabled '
      id: 3314e9aa-4546-49ca-809a-e441b344f5f2
      iscommand: false
      name: Is Kennav2 enabled?
      type: condition
      version: -1
    taskid: 3314e9aa-4546-49ca-809a-e441b344f5f2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 710
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4dcb3885-0d0e-4dd8-8a6d-744a3c57b9b8
      iscommand: false
      name: Kennav2
      type: title
      version: -1
    taskid: 4dcb3885-0d0e-4dd8-8a6d-744a3c57b9b8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 570
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          root: inputs.CVE_ID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for vulnerabilities in Kenna.
      id: 8a816485-5157-4566-8336-291b4f7fa4d0
      iscommand: true
      name: Search CVE with Kenna
      script: '|||kenna-search-vulnerabilities'
      tags:
      - autoCVEsearch
      type: regular
      version: -1
    taskid: 8a816485-5157-4566-8336-291b4f7fa4d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 910
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae99de5a-7c26-4cf6-87fc-d004af1cb212
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ae99de5a-7c26-4cf6-87fc-d004af1cb212
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1690
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Vulnerabilities
                root: Kenna
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: If found Assets with the given CVE
      id: cffb6924-0a75-4ed9-89d3-33944c6d31b2
      iscommand: false
      name: Found results?
      type: condition
      version: -1
    taskid: cffb6924-0a75-4ed9-89d3-33944c6d31b2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 1105
        }
      }
  "12":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Breached Compromised Hosts
      output:
        complex:
          accessor: Assets
          root: Kenna
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: AssetID
          root: Kenna.Vulnerabilities
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for assets.
      id: 5dc657f4-1a09-4466-87e0-c4e6aa568d3c
      iscommand: true
      name: Get hostname from assetID
      script: '|||kenna-search-assets'
      type: regular
      version: -1
    taskid: 5dc657f4-1a09-4466-87e0-c4e6aa568d3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 1330
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 536cbf27-e426-49ec-8746-d74a6912cf81
      iscommand: false
      name: RiskSense
      type: title
      version: -1
    taskid: 536cbf27-e426-49ec-8746-d74a6912cf81
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 800,
          "y": 570
        }
      }
  "14":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isEqualString
          right:
            value:
              simple: RiskSense
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Checks if RiskSense is enabled '
      id: 44395589-60e0-4dd1-893b-15b0aad442c3
      iscommand: false
      name: 'Is RiskSense Enabled? '
      type: condition
      version: -1
    taskid: 44395589-60e0-4dd1-893b-15b0aad442c3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 800,
          "y": 710
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      CVES:
        complex:
          root: inputs.CVE_ID
      TagName:
        simple: FireEye RedTeam tools
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      id: 126fda72-2bab-4baf-8d62-6995d6b9a270
      iscommand: false
      name: CVE Exposure - RiskSense
      playbookName: CVE Exposure - RiskSense
      type: playbook
      version: -1
    taskid: 126fda72-2bab-4baf-8d62-6995d6b9a270
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 790,
          "y": 910
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Endpoint
      value:
        complex:
          accessor: Host
          filters:
          - - left:
                iscontext: true
                value:
                  simple: RiskSense
              operator: isExists
          root: RiskSense
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered. If no value is
        entered, the script doesn't do anything.
      id: 38fa22d3-111a-4edb-8e4b-407af0cc699b
      iscommand: false
      name: Set results to Endpoint context
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 38fa22d3-111a-4edb-8e4b-407af0cc699b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 790,
          "y": 1105
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint
      value:
        complex:
          accessor: Assets
          root: Kenna
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered. If no value is
        entered, the script doesn't do anything.
      id: 97583f7a-e6b3-4662-86be-7e267e2539ac
      iscommand: false
      name: Set results to Endpoint context
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 97583f7a-e6b3-4662-86be-7e267e2539ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1410,
          "y": 1510
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_12_yes": 0.68,
      "11_9_#default#": 0.1,
      "14_9_#default#": 0.1,
      "1_2_yes": 0.16,
      "1_9_#default#": 0.1,
      "4_9_#default#": 0.1,
      "6_9_#default#": 0.1
    },
    "paper": {
      "dimensions": {
        "height": 1695,
        "width": 1810,
        "x": -20,
        "y": 60
      }
    }
  }
