contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.5.1
    packID: Whois
    packName: Whois
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook compares the domain registrant against the Cortex XSOAR
  list of approved registrants provided in the inputs. A registrant is the company
  or entity that owns the domain.
id: TIM - Process Domain Registrant With Whois
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: The Cortex XSOAR list name that contains the approved registrars.  A
    registrant is the company or entity  that owns the domain.
  key: ApprovedregistrantsListName
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    A one-character string used to delimit fields. This must match the value that you defined in the list separator server configuration.
    The default value is a comma, however, as registrants might contain the "," character in their name,
    Cortex XSOAR recommends that you select a different delimiter.
  key: RegistrantListDelimiter
  playbookInputQuery: null
  required: false
  value:
    simple: ','
- description: This input receives the Whois results from the parent playbook.
  key: WhoisResults
  playbookInputQuery: null
  required: false
  value: {}
name: TIM - Process Domain Registrant With Whois
outputs:
- contextPath: RegistrantDomainNotInList
  description: Domains for which the registrant wasn't in the list.
  type: string
- contextPath: RegistrantDomainInList
  description: Domains for which the registrant was in the list.
  type: string
- contextPath: DomainsNotResolvedByWhois
  description: Domains which Whois wasn't able to resolve.
  type: string
- contextPath: DomainsNotProcessed
  description: In case no registrant list was provided all domains will be outputted
    to this context path.
  type: string
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 56443fa8-222d-4859-8feb-fd9e7b202053
      iscommand: false
      name: ""
      version: -1
    taskid: 56443fa8-222d-4859-8feb-fd9e7b202053
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -240
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Results
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8f996d46-fb1d-4680-88cd-a3d222d5a167
      iscommand: false
      name: Are there query results?
      type: condition
      version: -1
    taskid: 8f996d46-fb1d-4680-88cd-a3d222d5a167
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9ac9f838-21c1-4381-8745-6ebcab8da602
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9ac9f838-21c1-4381-8745-6ebcab8da602
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1420
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      delimiter:
        simple: ${inputs.RegistrantListDelimiter}
      ignorecase:
        simple: "yes"
      listname:
        simple: ${inputs.ApprovedregistrantsListName}
      matchexact:
        simple: "yes"
      values:
        simple: ${Results.Whois.Registrant.organization}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the specified item is in a list. The default list
        is the Cortex XSOAR Indicators Allow list.
      id: 44b28e9c-3040-4919-8edf-98c2861fabbc
      iscommand: false
      name: FilterByList
      script: FilterByList
      type: regular
      version: -1
    taskid: 44b28e9c-3040-4919-8edf-98c2861fabbc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -70,
          "y": 480
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ApprovedregistrantsListName
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "13"
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 50b702d1-0484-4baa-87e7-ce371bc4b0b8
      iscommand: false
      name: Is there an approved registrants list?
      type: condition
      version: -1
    taskid: 50b702d1-0484-4baa-87e7-ce371bc4b0b8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -60,
          "y": 270
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: DomainsNotProcessed
      value:
        complex:
          accessor: Whois.QueryValue
          root: Results
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value into the context with the given context key
      id: 051e749a-0df6-4aed-8aa1-bbaad5b3f6a5
      iscommand: false
      name: Set domains that couldn't be processed
      script: Set
      type: regular
      version: -1
    taskid: 051e749a-0df6-4aed-8aa1-bbaad5b3f6a5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 730,
          "y": 1230
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Results.Whois.QueryResult
          operator: isNotEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2a35a5b3-1824-4906-8666-be31cf6651b1
      iscommand: false
      name: Are there domains without Whois query results?
      type: condition
      version: -1
    taskid: 2a35a5b3-1824-4906-8666-be31cf6651b1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -1260,
          "y": 480
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: no_whois_resolution
      indicatorsValues:
        simple: ${DomainsNotResolvedByWhois}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Tag indicator with the no_whois_result tag.
      id: fd92dde4-0bda-406e-8402-2307582a68c6
      iscommand: true
      name: Tag domain with no Whois resolution
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: fd92dde4-0bda-406e-8402-2307582a68c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -1260,
          "y": 1250
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ApprovedRegistrantDomains
      value:
        complex:
          accessor: Whois.QueryValue
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Results.Whois.Registrant.organization
              operator: inList
              right:
                iscontext: true
                value:
                  simple: List.In
          root: Results
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Domains whose registrant appears in the list defined in the inputs.ApprovedregistrantsListName
        context key are added to ApprovedDomains in context.
      id: d619742c-2c27-4a60-8156-e877eba9030d
      iscommand: false
      name: Set domains by approved registrants
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: d619742c-2c27-4a60-8156-e877eba9030d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -320,
          "y": 1045
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonApprovedRegistrantDomains
      value:
        complex:
          accessor: Whois.QueryValue
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Results.Whois.Registrant.organization
              operator: inList
              right:
                iscontext: true
                value:
                  simple: List.NotIn
          root: Results
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      id: f7130c8f-83a1-4b6d-89ec-8d6018251e31
      iscommand: false
      name: Set domains by non approved registrants
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: f7130c8f-83a1-4b6d-89ec-8d6018251e31
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1220
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bc5363dd-1f51-4e66-89d2-12a52b46dec3
      iscommand: false
      name: No registrant list provided
      type: title
      version: -1
    taskid: bc5363dd-1f51-4e66-89d2-12a52b46dec3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 730,
          "y": 480
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c17301fa-f768-4889-8bc1-2ab05c94b019
      iscommand: false
      name: Domain not found by Whois
      type: title
      version: -1
    taskid: c17301fa-f768-4889-8bc1-2ab05c94b019
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -1260,
          "y": 970
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 87cf4728-0a47-4ca4-854e-b5da694d87fe
      iscommand: false
      name: Domain registrant in approved list
      type: title
      version: -1
    taskid: 87cf4728-0a47-4ca4-854e-b5da694d87fe
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -230,
          "y": 670
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a8d7d880-46c3-4b04-8ca9-0394a42f1c88
      iscommand: false
      name: Domain registrant not in approved list
      type: title
      version: -1
    taskid: a8d7d880-46c3-4b04-8ca9-0394a42f1c88
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 240,
          "y": 670
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Results
      value:
        simple: ${inputs.WhoisResults}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value into the context with the given context key
      id: 55884370-bce5-43b9-8daa-ce8e94c99240
      iscommand: false
      name: Set Results
      script: Set
      type: regular
      version: -1
    taskid: 55884370-bce5-43b9-8daa-ce8e94c99240
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -90
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: approved_registrant
      indicatorsValues:
        simple: ${ApprovedRegistrantDomains}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Tags the indicator with the approved_registrant tag.
      id: 66b81388-3784-4887-85e2-d4ac600e80f1
      iscommand: true
      name: Tag as approved registrant
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 66b81388-3784-4887-85e2-d4ac600e80f1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -320,
          "y": 1220
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: DomainsNotResolvedByWhois
      value:
        complex:
          accessor: Whois.QueryValue
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Results.Whois.QueryResult
              operator: isNotEqualString
              right:
                value:
                  simple: "true"
          root: Results
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets a value into the context with the given context key
      id: f1b25a8e-a6ae-41ab-8f3d-30689c64b0a8
      iscommand: false
      name: Set domains without Whois results
      script: Set
      type: regular
      version: -1
    taskid: f1b25a8e-a6ae-41ab-8f3d-30689c64b0a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -1260,
          "y": 1100
        }
      }
  "28":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: List.In
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 51971516-ed0b-4150-8b78-d7ccbf90506b
      iscommand: false
      name: Are there there domains with an approved registrant?
      type: condition
      version: -1
    taskid: 51971516-ed0b-4150-8b78-d7ccbf90506b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -90,
          "y": 875
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 2370,
        "x": -1260,
        "y": -240
      }
    }
  }
