contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This playbook is used to block files from running on endpoints. \nThis
  playbook supports the following integrations:\n- Palo Alto Networks Traps\n- Palo
  Alto Networks Cortex XDR\n- Cybereason\n- Carbon Black Enterprise Response\n- Cylance
  Protect v2\n"
id: Block File - Generic v2
inputs:
- description: The MD5 hash of the file you want to block.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: The SHA256 hash of the file you want to block.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: In this input you can insert either MD5 or SHA256 that you wish to
    block.
  key: Hash
  playbookInputQuery: null
  required: false
  value: {}
name: Block File - Generic v2
outputs:
- contextPath: CbResponse.BlockedHashes.LastBlock.Time
  description: Last block time
- contextPath: CbResponse.BlockedHashes.LastBlock.Hostname
  description: Last block hostname
- contextPath: CbResponse.BlockedHashes.LastBlock.CbSensorID
  description: Last block sensor ID
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "10"
      - "11"
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
      iscommand: false
      name: ""
      version: -1
    taskid: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      MD5:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Hash
              operator: stringHasLength
              right:
                value:
                  simple: "32"
          root: inputs.Hash
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.MD5
            operator: append
          - operator: uniq
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook receives an MD5 hash and adds it to the block list in Carbon Black Enterprise Response. Files with that MD5 hash are blocked from execution on the managed endpoints.

        If the integration is disabled at the time of running, or if the hash is already on the block list, no action is taken on the MD5.
      id: 5a2f437e-234a-43ef-858d-28d07fd1c7c2
      iscommand: false
      name: Block File - Carbon Black Response
      playbookName: Block File - Carbon Black Response
      type: playbook
      version: -1
    taskid: 5a2f437e-234a-43ef-858d-28d07fd1c7c2
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 515
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      MD5:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Hash
              operator: stringHasLength
              right:
                value:
                  simple: "32"
          root: inputs.Hash
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.MD5
            operator: append
          - operator: uniq
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts an MD5 hash and blocks the file using the
        Cybereason integration.
      id: 2efe2a1a-1d31-438c-828f-b6ae50f3899d
      iscommand: false
      name: Block File - Cybereason
      playbookName: Block File - Cybereason
      type: playbook
      version: -1
    taskid: 2efe2a1a-1d31-438c-828f-b6ae50f3899d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      SHA256:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Hash
              operator: stringHasLength
              right:
                value:
                  simple: "64"
          root: inputs.Hash
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.SHA256
            operator: append
          - operator: uniq
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts a SHA256 hash and adds the hash to the Global
        Quarantine list using the Cylance Protect v2 integration.
      id: a887370c-f94a-42f9-866f-2d80b7707f41
      iscommand: false
      name: Block File - Cylance Protect v2
      playbookName: Block File - Cylance Protect v2
      type: playbook
      version: -1
    taskid: a887370c-f94a-42f9-866f-2d80b7707f41
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 340
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32d4b47a-e972-4e30-875b-b563130cc4ca
      iscommand: false
      name: Cybereason
      type: title
      version: -1
    taskid: 32d4b47a-e972-4e30-875b-b563130cc4ca
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c07d0e1-59b1-436c-8e90-f2d0410df813
      iscommand: false
      name: Carbon Black Enterprise Response
      type: title
      version: -1
    taskid: 0c07d0e1-59b1-436c-8e90-f2d0410df813
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
      iscommand: false
      name: Cylance Protect v2
      type: title
      version: -1
    taskid: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b42b03dd-99c1-4149-8c32-336d23b88cf0
      iscommand: false
      name: Palo Alto Cortex XDR
      type: title
      version: -1
    taskid: b42b03dd-99c1-4149-8c32-336d23b88cf0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      HashList:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Hash
              operator: stringHasLength
              right:
                value:
                  simple: "64"
          root: inputs.Hash
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.SHA256
            operator: append
          - operator: uniq
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Use this playbook to add files to Cortex XDR block list with a
        given file SHA256 playbook input.
      id: cfefcb2a-3dcf-44a5-8aed-ef231d7fe00b
      iscommand: false
      name: Cortex XDR - Block File
      playbookName: Cortex XDR - Block File
      type: playbook
      version: -1
    taskid: cfefcb2a-3dcf-44a5-8aed-ef231d7fe00b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 530,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
