contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.1.4
    packID: PAN-OS
    packName: PAN-OS by Palo Alto Networks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Network operations playbook that updates the version and content of the
  firewall. You must have Superuser permissions to update the PAN-OS version.
id: NetOps - Firewall Version and Content Upgrade
inputs:
- description: Target PAN-OS version to which to upgrade.
  key: target_version
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: targetfirewallversion
      root: incident
name: NetOps - Firewall Version and Content Upgrade
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b7fe4fdf-e359-4010-89e6-60b4c288f797
      iscommand: false
      name: ""
      version: -1
    taskid: b7fe4fdf-e359-4010-89e6-60b4c288f797
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 700,
          "y": -210
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: true
    quietmode: 0
    reputationcalc: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Downloads the latest content update.
      id: e540b70a-08b7-4979-8266-aa503a1e3500
      iscommand: true
      name: Download the latest content update
      script: Panorama|||pan-os-download-latest-content-update
      type: regular
      version: -1
    taskid: e540b70a-08b7-4979-8266-aa503a1e3500
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": -40
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      job_id:
        complex:
          accessor: Content.Download.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Checks content update download status.
      id: dac55564-0c88-4e85-80e0-74af6b9b4990
      iscommand: true
      name: Check on the content download status
      script: Panorama|||pan-os-content-update-download-status
      type: regular
      version: -1
    taskid: dac55564-0c88-4e85-80e0-74af6b9b4990
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 180
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Installs the latest content update.
      id: b28debf8-d54b-42b3-841c-5ebfad3cfde6
      iscommand: true
      name: Install the latest content update
      script: Panorama|||pan-os-install-latest-content-update
      type: regular
      version: -1
    taskid: b28debf8-d54b-42b3-841c-5ebfad3cfde6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 570
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      job_id:
        complex:
          accessor: Content.Install.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Checks on the content update install status.
      id: c342a8fd-a87d-4057-8edb-35ecc623ff88
      iscommand: true
      name: Check on the content installation status
      script: Panorama|||pan-os-content-update-install-status
      type: regular
      version: -1
    taskid: c342a8fd-a87d-4057-8edb-35ecc623ff88
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 760
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Checks the PAN-OS software version from the repository.
      id: 5f5091be-db9d-4914-80ff-5b4b151a1400
      iscommand: true
      name: Check for the latest PAN-OS software
      script: Panorama|||pan-os-check-latest-panos-software
      type: regular
      version: -1
    taskid: 5f5091be-db9d-4914-80ff-5b4b151a1400
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1150
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      target_version:
        complex:
          root: inputs.target_version
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Downloads target PAN-OS version to be installed.
      id: 90d3c358-46d3-4ea6-8508-2cddf6e962e5
      iscommand: true
      name: Download the latest PAN-OS software update
      script: Panorama|||pan-os-download-panos-version
      type: regular
      version: -1
    taskid: 90d3c358-46d3-4ea6-8508-2cddf6e962e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1340
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      target_version:
        complex:
          root: inputs.target_version
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Installs the target PAN-OS version.
      id: 4f33c545-4fd5-485e-8b92-cc3e4689412e
      iscommand: true
      name: Install the latest PAN-OS software update
      script: Panorama|||pan-os-install-panos-version
      type: regular
      version: -1
    taskid: 4f33c545-4fd5-485e-8b92-cc3e4689412e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1930
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        complex:
          accessor: PANOS.Install.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Checks the PAN-OS installation status.
      id: 28a4fb31-0ae2-40e4-804d-692bd0aca523
      iscommand: true
      name: Check on the PAN-OS software installation status
      script: Panorama|||pan-os-install-panos-status
      type: regular
      version: -1
    taskid: 28a4fb31-0ae2-40e4-804d-692bd0aca523
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2110
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Reboots the Firewall device.
      id: ebcba4bf-20e6-40f5-87b5-410847e31c04
      iscommand: true
      name: Reboot the firewall
      script: Panorama|||pan-os-device-reboot
      type: regular
      version: -1
    taskid: ebcba4bf-20e6-40f5-87b5-410847e31c04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2520
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Content.Download.JobID
          root: Panorama
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: pan-os-content-update-download-status
      Timeout:
        simple: "10"
      dt:
        simple: Panorama.Content.Download(val.Status !== 'Completed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 14794c89-6d30-463a-812c-9e93b4e5f710
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 14794c89-6d30-463a-812c-9e93b4e5f710
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": 370
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Content.Install.JobID
          root: Panorama
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: pan-os-content-update-install-status
      Timeout:
        simple: "10"
      dt:
        simple: Panorama.Content.Install(val.Status !== 'Completed' && val.Status
          !== 'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 6ed771e0-1ce5-47b4-89ea-15635a0cf374
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 6ed771e0-1ce5-47b4-89ea-15635a0cf374
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": 960
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        complex:
          accessor: PANOS.Download.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: PAN-OS download status
      id: 33afd485-aeef-49c6-83fb-23250779f58e
      iscommand: true
      name: Download PAN-OS Status
      script: Panorama|||pan-os-download-panos-status
      type: regular
      version: -1
    taskid: 33afd485-aeef-49c6-83fb-23250779f58e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1540
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: PANOS.Download.JobID
          root: Panorama
      Interval:
        simple: "10"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: pan-os-download-panos-status
      Timeout:
        simple: "20"
      dt:
        simple: Panorama.PANOS.Download(val.Status !== 'Completed' && val.Status !==
          'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: c74d8f1c-3dbd-49f9-8b94-59a9007a0a1c
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: c74d8f1c-3dbd-49f9-8b94-59a9007a0a1c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1740
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: PANOS.Install.JobID
          root: Panorama
      Interval:
        simple: "10"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: pan-os-install-panos-status
      Timeout:
        simple: "20"
      dt:
        simple: Panorama.PANOS.Install(val.Status !== 'Completed' && val.Status !==
          'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: cafe7cfd-7bb9-4caf-8cd5-dd6aaab69dd5
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: cafe7cfd-7bb9-4caf-8cd5-dd6aaab69dd5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": 2320
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2825,
        "width": 380,
        "x": 700,
        "y": -210
      }
    }
  }
