contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.6.10
    packID: VirusTotal
    packName: VirusTotal
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Detonate one or more files using the VirusTotal integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
id: Detonate File - VirusTotal
inputs:
- description: The file to detonate. The file is taken from the context.
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
- description: Polling frequency - how often the polling command should run (minutes)
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: How much time to wait before a timeout occurs (minutes)
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "15"
name: Detonate File - VirusTotal
outputs:
- contextPath: File.MD5
  description: File's MD5
  type: string
- contextPath: File.SHA1
  description: File's SHA1
  type: string
- contextPath: File.SHA256
  description: File's SHA256
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that determined the file is malicious.
  type: string
- contextPath: File.Malicious.Detections
  description: For malicious files, the total number of detections.
  type: number
- contextPath: File.Malicious.TotalEngines
  description: For malicious files, the total number of engines.
  type: number
- contextPath: DBotScore.Indicator
  description: The indicator we tested.
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator.
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: File.VirusTotal.Scans.Source
  description: The vendor used to scan this hash.
  type: string
- contextPath: File.VirusTotal.Scans.Detected
  description: Scan detection for this hash (True,False).
  type: boolean
- contextPath: File.VirusTotal.Scans.Result
  description: Scan result for this hash - signature, etc.
  type: string
- contextPath: File.SSDeep
  description: The ssdeep value for the file.
  type: string
- contextPath: File.Type
  description: File type as determined by Virus Total.
  type: string
- contextPath: File.Size
  description: File size, in bytes.
  type: number
- contextPath: File.VirusTotal.Tags
  description: Virus Total file tags.
  type: string
- contextPath: File.Tags
  description: File tags.
  type: string
- contextPath: File.VirusTotal.MagicLiteral
  description: File magic literals.
  type: string
- contextPath: File.VirusTotal.FirstSeen
  description: Time where the file was first seen.
  type: string
- contextPath: File.VirusTotal.CommunityReputation
  description: Community reputation of the file.
  type: number
- contextPath: File.VirusTotal.CommunityComments
  description: Community comments about the file.
  type: string
- contextPath: File.VirusTotal.AuthentiHash
  description: AuthentiHash of the file.
  type: string
- contextPath: File.Authentihash
  description: AuthentiHash of the file.
  type: string
- contextPath: File.VirusTotal.ImpHash
  description: ImpHash of the file.
  type: string
- contextPath: VirusTotal.ID
  description: The ID of the file uploaded to VirusTotal. (The file hash)
  type: String
- contextPath: VirusTotal.Status
  description: The status of the queried file. Could be "Queued" or "Ready".
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 489b704c-bef9-40e7-8aa8-f74cca308a94
      iscommand: false
      name: ""
      version: -1
    taskid: 489b704c-bef9-40e7-8aa8-f74cca308a94
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${vtScanID}
      PollingCommandArgName:
        simple: resource
      PollingCommandName:
        simple: vt-private-get-file-report
      dt:
        simple: VirusTotal(val.Status!=='Ready').ID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:
        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: ed9dfa38-c4f9-418d-8985-24aef81e5b82
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: ed9dfa38-c4f9-418d-8985-24aef81e5b82
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1085
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: finished
      id: e589b774-3cee-4dff-8e14-788ef3590dfa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e589b774-3cee-4dff-8e14-788ef3590dfa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 70,
          "y": 1945
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: VirusTotal - Private API
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verify that there is a valid instance of Virus Total enabled.
      id: 13ecb287-26bc-43e0-8208-c7fe73ced470
      iscommand: false
      name: Is VirusTotal enabled?
      type: condition
      version: -1
    taskid: 13ecb287-26bc-43e0-8208-c7fe73ced470
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 185
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|SYS|DLL|COM|SCR|CPL|OCX|CGI|DOC|DOTM|DOCX|DOTX|XLS|PPAM|XSLX|PPS|XLSB|PPSX|XLSM|PPSM|PPT|PPTX|PPTM|RTF|SHS|XLTM|SLDM|XLTX|SLDX|XLAM|THMX|DOCM|XAR|JTD|JTDC|PDF|SWF|GZ|7Z|TGZ|MSI|ZIP|LZH|CAB|LZMA|APK|JAR|CLASS|JPEG|PNG|GIF|CMD|ACE|BAT|ARJ|VBS|CHM|XML|LNK|URL|MOF|HTM|OCX|HTML|POTM|EML|POTX|MSG|PS1|VB|REG|VBA|WSC|VBE|WSF|VBS|WSH)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|SYS|DLL|COM|SCR|CPL|OCX|CGI|DOC|DOTM|DOCX|DOTX|XLS|PPAM|XSLX|PPS|XLSB|PPSX|XLSM|PPSM|PPT|PPTX|PPTM|RTF|SHS|XLTM|SLDM|XLTX|SLDX|XLAM|THMX|DOCM|XAR|JTD|JTDC|PDF|SWF|GZ|7Z|TGZ|MSI|ZIP|LZH|CAB|LZMA|APK|JAR|CLASS|JPEG|PNG|GIF|CMD|ACE|BAT|ARJ|VBS|CHM|XML|LNK|URL|MOF|HTM|OCX|HTML|POTM|EML|POTX|MSG|PS1|VB|REG|VBA|WSC|VBE|WSF|VBS|WSH)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|SYS|DLL|COM|SCR|CPL|OCX|CGI|DOC|DOTM|DOCX|DOTX|XLS|PPAM|XSLX|PPS|XLSB|PPSX|XLSM|PPSM|PPT|PPTX|PPTM|RTF|SHS|XLTM|SLDM|XLTX|SLDX|XLAM|THMX|DOCM|XAR|JTD|JTDC|PDF|SWF|GZ|7Z|TGZ|MSI|ZIP|LZH|CAB|LZMA|APK|JAR|CLASS|JPEG|PNG|GIF|CMD|ACE|BAT|ARJ|VBS|CHM|XML|LNK|URL|MOF|HTM|OCX|HTML|POTM|EML|POTX|MSG|PS1|VB|REG|VBA|WSC|VBE|WSF|VBS|WSH)\b
                root: File
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if file type is supported.
      id: d8e19b0c-3dfa-41f8-86fa-2d12ff711340
      iscommand: false
      name: Is file type supported?
      type: condition
      version: -1
    taskid: d8e19b0c-3dfa-41f8-86fa-2d12ff711340
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File
      value:
        complex:
          root: inputs.File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set the file object into context.
      id: 3814f559-a639-4e80-8d6e-c74b9e96e495
      iscommand: false
      name: Set File to context
      script: Set
      type: regular
      version: -1
    taskid: 3814f559-a639-4e80-8d6e-c74b9e96e495
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.File
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks that there is a file in the playbook inputs.
      id: 9b8022fc-dfd0-4806-8ead-65f53804065f
      iscommand: false
      name: Is there a file to detonate?
      type: condition
      version: -1
    taskid: 9b8022fc-dfd0-4806-8ead-65f53804065f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 370
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID}
          root: ${File
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal
      description: Submits a file for scanning.
      id: f2d814ea-409b-4e02-89e2-74a8c175b622
      iscommand: true
      name: VirusTotal upload file
      script: VirusTotal|||file-scan
      type: regular
      version: -1
    taskid: f2d814ea-409b-4e02-89e2-74a8c175b622
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1960,
        "width": 717.5,
        "x": 50,
        "y": 50
      }
    }
  }
