contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.1.1
    packID: TIM_SIEM
    packName: TIM - SIEM Integration
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook runs sub playbooks that send indicators to your SIEM. To select the indicators you want to add, go to playbook inputs, choose “from indicators” and set your query. For example tags:approved_black, approved_white etc. The purpose of the playbook is to send to SIEM only indicators that have been processed and tagged accordingly after an automatic or manual review process. The default playbook query is"
  (type:ip or type:file or type:Domain or type:URL) -tags:pending_review and (tags:approved_black or tags:approved_white or tags:approved_watchlist)"
  In case more indicator types need to be sent to the SIEM, the query must be edited accordingly.
id: TIM - Add All Indicator Types To SIEM
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: (type:ip or type:file or type:Domain or type:URL) -tags:pending_review
      and (tags:approved_black or tags:approved_white or tags:approved_watchlist)
      and expirationStatus:active
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
name: TIM - Add All Indicator Types To SIEM
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
      - "5"
      - "7"
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb42f4ee-dd78-4c62-853d-6a45f75e21a7
      iscommand: false
      name: ""
      version: -1
    taskid: eb42f4ee-dd78-4c62-853d-6a45f75e21a7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -430
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook pushes to your SIEM indicators that have the tag
        processed_black. These indicators have been either received by a reliable
        Threat Intel feed or approved by an analyst manually.
      id: e71aedcf-fdf6-4749-8033-354298bcfff1
      iscommand: false
      name: TIM - Add IP Indicators To SIEM
      playbookId: TIM - Add IP Indicators To SIEM
      type: playbook
      version: -1
    taskid: e71aedcf-fdf6-4749-8033-354298bcfff1
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": -100
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 00e7d9f8-86af-4053-830a-3cc848c887bc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 00e7d9f8-86af-4053-830a-3cc848c887bc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: IP
                root: playbookQuery
                transformers:
                - operator: uniq
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 83477e4d-c432-490a-8bba-009202a88e25
      iscommand: false
      name: Are there IP results?
      type: condition
      version: -1
    taskid: 83477e4d-c432-490a-8bba-009202a88e25
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 200,
          "y": -270
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: File
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.CustomFields.tags
                    operator: isEqualString
                    right:
                      value:
                        simple: approved_black
                root: playbookQuery
                transformers:
                - operator: uniq
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 729aef8f-984e-41a4-8486-eafe3a4731c8
      iscommand: false
      name: Are there bad Hash results?
      type: condition
      version: -1
    taskid: 729aef8f-984e-41a4-8486-eafe3a4731c8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 700,
          "y": -270
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8d713b29-1486-45a6-8280-c71965b11c17
      iscommand: false
      name: TIM - Add Bad Hash Indicators To SIEM
      playbookId: TIM - Add Bad Hash Indicators To SIEM
      type: playbook
      version: -1
    taskid: 8d713b29-1486-45a6-8280-c71965b11c17
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 870,
          "y": -100
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: Domain
                root: playbookQuery
                transformers:
                - operator: uniq
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d461c70-df64-4f0a-88e1-fbedeac33467
      iscommand: false
      name: Are there Domain results?
      type: condition
      version: -1
    taskid: 9d461c70-df64-4f0a-88e1-fbedeac33467
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1510,
          "y": -270
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: URL
                root: playbookQuery
                transformers:
                - operator: uniq
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fe4263f-2c8e-494c-8cbf-0f0ef4a4d27a
      iscommand: false
      name: Are there URL results?
      type: condition
      version: -1
    taskid: 7fe4263f-2c8e-494c-8cbf-0f0ef4a4d27a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -670,
          "y": -270
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 202e48ee-1193-4afc-8ad7-a21d49eaf97b
      iscommand: false
      name: TIM - Add Domain Indicators To SIEM
      playbookId: TIM - Add Domain Indicators To SIEM
      type: playbook
      version: -1
    taskid: 202e48ee-1193-4afc-8ad7-a21d49eaf97b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1680,
          "y": -100
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f85efed7-c95e-403f-8092-c14ebc6d5ae0
      iscommand: false
      name: TIM - Add Url Indicators To SIEM
      playbookId: TIM - Add Url Indicators To SIEM
      type: playbook
      version: -1
    taskid: f85efed7-c95e-403f-8092-c14ebc6d5ae0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -840,
          "y": -100
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 565,
        "width": 2900,
        "x": -840,
        "y": -430
      }
    }
  }
