contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 3.5.30
    packID: Phishing
    packName: Phishing
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook retrieves the original email in a thread, including headers and attachments, when the reporting user forwarded the original email not as an attachment.
  Note:\ You must have the necessary eDiscovery permissions in the EWS integration to execute a global search.
id: get_original_email_-_ews
inputs:
- description: Email address of the reporting user.
  key: Mailbox
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: labels.Email/from
      root: incident
- description: The InReplyTo header in the forwarded email.
  key: InReplyTo
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: labels.Email/Header/In-Reply-To
      root: incident
- description: The ThreadTopic header in the forwarded email.
  key: ThreadTopic
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: labels.Email/Header/Thread-Topic
      root: incident
name: Get Original Email - EWS
outputs:
- contextPath: Email
  description: The email object
  type: unknown
- contextPath: Email.To
  description: The email recipient.
  type: string
- contextPath: Email.From
  description: The email sender.
  type: string
- contextPath: Email.HTML
  description: The email HTML.
  type: string
- contextPath: Email.Body
  description: The email text body.
  type: string
- contextPath: Email.Headers
  description: The email headers.
  type: unknown
- contextPath: Email.Subject
  description: The email subject.
  type: string
- contextPath: File
  description: The original attachments.
  type: unknown
- contextPath: Email.HeadersMap
  description: The email headers map.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5607d1c6-85b0-4181-8b10-bb3a5b113c6f
      iscommand: false
      name: ""
      version: -1
    taskid: 5607d1c6-85b0-4181-8b10-bb3a5b113c6f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: EWS v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verifies an active instance of the EWS v2 integration is enabled.
      id: 03f2c080-1995-42fc-82ce-16d474fb5438
      iscommand: false
      name: Is EWS v2 enabled?
      type: condition
      version: -1
    taskid: 03f2c080-1995-42fc-82ce-16d474fb5438
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d2eca123-db35-4b27-88d8-a8b77ffd6784
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d2eca123-db35-4b27-88d8-a8b77ffd6784
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -60,
          "y": 1840
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.InReplyTo
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.ThreadTopic
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Mailbox
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verifies the required input values for retrieving the original
        email exist.
      id: b2617aaf-5e54-43f5-89fe-82fc78cd099b
      iscommand: false
      name: Verify required inputs
      type: condition
      version: -1
    taskid: b2617aaf-5e54-43f5-89fe-82fc78cd099b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      query:
        simple: subject:"${inputs.ThreadTopic}"
      selected-fields:
        simple: in_reply_to
      target-mailbox:
        complex:
          root: inputs.Mailbox
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Retrieves all messages found in the forwarded email thread.
      id: f3c1bfda-b3c0-4c7c-8fce-fb180ff6fd07
      iscommand: true
      name: Search for messages by Thread-Topic
      script: EWS v2|||ews-search-mailbox
      type: regular
      version: -1
    taskid: f3c1bfda-b3c0-4c7c-8fce-fb180ff6fd07
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 545
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: messageId
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: EWSItem.messageId
                    operator: isEqualString
                    right:
                      iscontext: true
                      value:
                        simple: inputs.InReplyTo
                root: EWSItem
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verifies that an email object with a Message-Id matching the InReplyTo
        ID of the forwarded email was found.
      id: 25f6439f-778f-45a5-841a-53efe77d590c
      iscommand: false
      name: Was a matching email found?
      type: condition
      version: -1
    taskid: 25f6439f-778f-45a5-841a-53efe77d590c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 1070
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: EWSItem
      value:
        complex:
          accessor: Items
          root: EWS
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets the email object to context.
      id: c729f95f-bc75-477e-8000-14c99346873d
      iscommand: false
      name: Set context
      script: Set
      type: regular
      version: -1
    taskid: c729f95f-bc75-477e-8000-14c99346873d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      item-ids:
        complex:
          accessor: itemId
          filters:
          - - left:
                iscontext: true
                value:
                  simple: EWSItem.messageId
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.InReplyTo
          root: EWSItem
      target-mailbox:
        complex:
          root: inputs.Mailbox
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Gets the original email from the EWS server.
      id: 6f28ff90-80ff-414e-819b-310a51183da4
      iscommand: true
      name: Get original email
      script: EWS v2|||ews-get-items
      type: regular
      version: -1
    taskid: 6f28ff90-80ff-414e-819b-310a51183da4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1245
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: EWS
      subplaybook:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Deletes the email object from context.
      id: 8764cbb0-dd56-4095-8df2-e77035713e2e
      iscommand: false
      name: Delete old context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 8764cbb0-dd56-4095-8df2-e77035713e2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 895
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Email
      value:
        simple: '${.={Subject: val[''EWS''][''Items''][''subject''], To: val[''EWS''][''Items''][''toRecipients''],
          From: val[''EWS''][''Items''][''sender''], Text: val[''EWS''][''Items''][''textBody''],HTML:
          val[''EWS''][''Items''][''body''], Headers: val[''EWS''][''Items''][''headers''],
          ''HeadersMap'': val[''Email''][''0''][''HeadersMap''] }}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sets the playbook outputs to context.
      id: 91028b3f-61f2-4383-8bfd-eff9dd01af96
      iscommand: false
      name: Set output
      script: Set
      type: regular
      version: -1
    taskid: 91028b3f-61f2-4383-8bfd-eff9dd01af96
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": 1595
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Items.itemId
                root: EWS
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "11"
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verifies the original email is in context.
      id: 75ab61a9-a6cf-4d74-842f-67436507b8f4
      iscommand: false
      name: Was the original email found?
      type: condition
      version: -1
    taskid: 75ab61a9-a6cf-4d74-842f-67436507b8f4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1420
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      item-id:
        complex:
          accessor: Items.itemId
          root: EWS
      target-mailbox:
        complex:
          root: inputs.Mailbox
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWS v2
      description: Retrieves the attachments of the original email from EWS, including
        file attachments and item attachments (such as other emails and calendar items).
      id: 427d5e37-2e56-4522-8e69-caabe8fd70d9
      iscommand: true
      name: Get attachments of the original email
      script: EWS v2|||ews-get-attachment
      type: regular
      version: -1
    taskid: 427d5e37-2e56-4522-8e69-caabe8fd70d9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 397.5,
          "y": 1595
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1855,
        "width": 1267.5,
        "x": -60,
        "y": 50
      }
    }
  }
