contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 3.5.30
    packID: Phishing
    packName: Phishing
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |
  Hunt indicators related to phishing with available integrations and then handle the results. Handling the results will include setting relevant incident fields which will be displayed in the layout and optionally, opening new incidents according to the findings.
  Current integration in this playbook:
  - Microsoft 365 Defender (using "Advanced Hunting")

  Note that this playbook should be used as a sub-playbook inside a phishing incident and not as a main playbook.
id: Phishing - Indicators Hunting
inputs:
- description: |-
    The DBotScore object containing these keys:
    - Indicator
    - Type
    - Score
  key: DBotScore
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: DBotScore
- description: When "True", the "Phishing - Handle Microsoft 365 Defender Results"
    sub-playbook will create new phishing incidents for each email that contains one
    of the malicious indicators. Default is "False".
  key: EmailHuntingCreateNewIncidents
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: The mailbox of the listening integration. In case it is provided, the
    emails found in it will be ignored.
  key: ListenerMailbox
  playbookInputQuery: null
  required: false
  value: {}
name: Phishing - Indicators Hunting
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae9d5f25-f689-44b5-8644-1d1ff8da2c53
      iscommand: false
      name: ""
      version: -1
    taskid: ae9d5f25-f689-44b5-8644-1d1ff8da2c53
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 1990
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        complex:
          accessor: Indicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: ip
          - - left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Score
              operator: isEqualString
              right:
                value:
                  simple: "3"
          root: inputs.DBotScore
      ListenerMailbox:
        complex:
          root: inputs.ListenerMailbox
      SHA256:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: file
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: hash
          - - left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Score
              operator: greaterThanOrEqual
              right:
                value:
                  simple: "3"
          - - left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Indicator
              operator: stringHasLength
              right:
                value:
                  simple: "64"
          root: inputs.DBotScore.Indicator
      URLDomain:
        complex:
          accessor: Indicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: URL
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: domain
          - - left:
                iscontext: true
                value:
                  simple: inputs.DBotScore.Score
              operator: greaterThanOrEqual
              right:
                value:
                  simple: "3"
          root: inputs.DBotScore
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |
        This playbook retrieves email data based on the `URLDomain`, `SHA256`, `IPAddress`, and `MessageID` inputs. The output will be a unified object with all of the retrieved emails based on the sub-playbooks outputs:

        - **Microsoft 365 Defender - Get Email URL clicks**:
                Retrieves data based on URL click events.


        - **Microsoft 365 Defender - Emails Indicators Hunt**:
                Retrieves data based on several different email events.

        Read the playbooks' descriptions in order to get the full details.
      id: f0a7a0b1-156d-4f73-8a68-e0c06661cb54
      iscommand: false
      name: Microsoft 365 Defender - Threat Hunting Generic
      playbookName: Microsoft 365 Defender - Threat Hunting Generic
      type: playbook
      version: -1
    taskid: f0a7a0b1-156d-4f73-8a68-e0c06661cb54
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 2150
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      CreateNewIncidents:
        complex:
          root: inputs.EmailHuntingCreateNewIncidents
      EmailBrand:
        simple: MicrosoftGraphMail
      RetrievedEmails:
        complex:
          accessor: RetrievedEmails
          root: Microsoft365Defender
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This playbook is used to handle the results from the "Microsoft 365 Defender - Threat Hunting Generic" playbook inside a phishing incident. It will perform the following actions:
        1) Set the relevant incident fields based on the results, such as "Clicked URLs", "Malicious URL Viewed", and "Malicious URL Clicked".
        2) In case the relevant playbook inputs were configured, it will create new incidents for each email returned in the results. First, it will try to retrieve the original emails' files and then it will create an incident for each retrieved email.
        3) Link the newly created incidents to the main originating incident.

        Note that this playbook should only be used inside a phishing incident and not as a main playbook.
      id: 45f91f5a-63cd-4eb1-89c5-9c4d45a9201e
      iscommand: false
      name: Phishing - Handle Microsoft 365 Defender Results
      playbookId: Phishing - Handle Microsoft 365 Defender Results
      type: playbook
      version: -1
    taskid: 45f91f5a-63cd-4eb1-89c5-9c4d45a9201e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 2560
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: RetrievedEmails
                root: Microsoft365Defender
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Did the previous task returned any emails in its output?
      id: e480e0e4-cf08-4ac6-8897-48cf53991382
      iscommand: false
      name: Any emails found using Microsoft 365 Defender?
      type: condition
      version: -1
    taskid: e480e0e4-cf08-4ac6-8897-48cf53991382
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 2345
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4a0761e3-523a-46c5-89d0-2e4daa11ebfc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4a0761e3-523a-46c5-89d0-2e4daa11ebfc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 2740
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "3_2_yes": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 1710,
        "y": 1990
      }
    }
  }
