contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |
  The playbook enables you to get all of the corresponding file hashes for a file even if there is only one hash type available.
  For example, if we have only the SHA256 hash, the playbook will get the SHA1 and MD5 hashes as long as the
  original searched hash is recognized by any our the threat intelligence integrations.
id: Convert file hash to corresponding hashes
inputs:
- description: The SHA256 hash on which to search.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: The SHA1 hash on which to search.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
- description: The MD5 hash on which to search.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
name: Convert file hash to corresponding hashes
outputs:
- contextPath: File.SHA256
  description: Output for detected SHA256 hash.
  type: string
- contextPath: File.SHA1
  description: Output for detected SHA1 hash.
  type: string
- contextPath: File.MD5
  description: Output for detected MD5 hash.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
      - "36"
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start
      id: f3d44d02-1482-4dd0-8055-34128346e4ec
      iscommand: false
      name: ""
      version: -1
    taskid: f3d44d02-1482-4dd0-8055-34128346e4ec
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 520,
          "y": -100
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: d0c581d2-789c-4a12-8940-37f17a47b4f6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d0c581d2-789c-4a12-8940-37f17a47b4f6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 520,
          "y": 970
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Does SHA256 hash exist?
      id: b797fdc7-1704-442a-8605-ee06bfb0bf54
      iscommand: false
      name: Does SHA256 hash exist?
      type: condition
      version: -1
    taskid: b797fdc7-1704-442a-8605-ee06bfb0bf54
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 970,
          "y": 240
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.MD5
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Does MD5 hash exist?
      id: f7142eb2-9483-4546-8d07-a828d636d0ad
      iscommand: false
      name: Does MD5 hash exist?
      type: condition
      version: -1
    taskid: f7142eb2-9483-4546-8d07-a828d636d0ad
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -250,
          "y": 240
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA1
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Does SHA1 hash exist?
      id: eff5d9b7-ea36-4310-8650-5e26fa38209e
      iscommand: false
      name: Does SHA1 hash exist?
      type: condition
      version: -1
    taskid: eff5d9b7-ea36-4310-8650-5e26fa38209e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 230
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      file:
        complex:
          root: inputs.SHA1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uses the SHA1 hash as a reference to check for other corresponding
        hashes of the same file.
      id: 65ff1c51-6bc1-4171-8bde-eb6ecb862f4e
      iscommand: true
      name: Get hashes by SHA1
      script: '|||file'
      type: regular
      version: -1
    taskid: 65ff1c51-6bc1-4171-8bde-eb6ecb862f4e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 410
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      file:
        complex:
          root: inputs.MD5
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uses the MD5 hash as a reference to check for other corresponding
        hashes of the same file.
      id: 9e3c8b51-dbc6-464a-8af7-f5d43b663bd4
      iscommand: true
      name: Get hashes by MD5
      script: '|||file'
      type: regular
      version: -1
    taskid: 9e3c8b51-dbc6-464a-8af7-f5d43b663bd4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -490,
          "y": 410
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      file:
        complex:
          root: inputs.SHA256
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uses the SHA256 hash as a reference to check for other corresponding
        hashes of the same file.
      id: 29ef7703-de75-4ff3-844c-a852e333bdbe
      iscommand: true
      name: Get Hashes by SHA256
      script: '|||file'
      type: regular
      version: -1
    taskid: 29ef7703-de75-4ff3-844c-a852e333bdbe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1230,
          "y": 410
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: MD5
      id: fdfd1cd9-3095-455b-8481-072b140ee5de
      iscommand: false
      name: MD5
      type: title
      version: -1
    taskid: fdfd1cd9-3095-455b-8481-072b140ee5de
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -250,
          "y": 115
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: SHA1
      id: a75bc19c-d514-44ab-885d-fb6664dd0b29
      iscommand: false
      name: SHA1
      type: title
      version: -1
    taskid: a75bc19c-d514-44ab-885d-fb6664dd0b29
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 520,
          "y": 115
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: SHA256
      id: a2d56e80-d468-46a0-891d-3792a6bf0bd9
      iscommand: false
      name: SHA256
      type: title
      version: -1
    taskid: a2d56e80-d468-46a0-891d-3792a6bf0bd9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 970,
          "y": 110
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_15_yes": 0.55,
      "9_16_yes": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 1135,
        "width": 2100,
        "x": -490,
        "y": -100
      }
    }
  }
